// Generated by https://Quicktype.in

import { IColumn } from "./ILibros";

export interface IClasificacion {
    id:          string;
    name:        string;
    descripcion: string;
    logo:        string;
}

const ColumClasificacion:IColumn[] = [
    {
        key: "name",
        label: "Nombre",
      },
      {
        key: "descripcion",
        label: "Titulo",
      },
      {
        key: "logo",
        label: "Imagen",
      },
];

export default ColumClasificacion;
